apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: ddaa
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433

          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ddaa-secret
                  key: MSSQL_SA_PASSWORD

          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-pvc