apiVersion: v1
kind: Secret
metadata:
  name: ddaa-secret
  namespace: ddaa
type: Opaque
stringData:
  # Usuario usado por el backend para conectarse a SQL Server.
  # Para la versión mínima se usará el usuario administrador sa.
  DDAA_DB_USER: "sa"

  # Debe ser una contraseña fuerte para SQL Server.
  # No subir contraseñas reales al repositorio.
  DDAA_DB_PASSWORD: "Cambiar_Esta_Clave_12345"

  # SQL Server Linux exige una contraseña fuerte para el usuario sa.
  MSSQL_SA_PASSWORD: "Cambiar_Esta_Clave_12345"